config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'
  devise_for :users

  resources :teachers, only: [:index, :show, :edit, :update]
  resources :students, only: [:index, :show]
  resources :lesson_plans, only: [:show]
  resources :lessons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    validates :hour, presence: true
    belongs_to :group
    belongs_to :teacher
    belongs_to :subject
    delegate :students, to: :group
    LESSON_TIME = 1
    validate :check_teacher_day_overlap, :check_group_day_overlap, :check_valid_hour, :check_at_least_one_day, :check_only_one_day


    def end_hour
        hour.hour + LESSON_TIME
    end

    def check_lesson_days
        array_days = %w[monday tuesday wednesday thursday friday]
        days = ""
        array_days.each { |day| days += (day.capitalize == "Friday" ? "Friday" : "#{day.capitalize}, ") if check_day(day) }
        days
    end

    def check_day(day)
        send("#{day}")
    end

    def find_students_in_lesson
        Student.where(group: group)
    end

    def to_s
        "#{self.subject.name} at #{self.hour.hour}:00 for Group #{self.group.group_number}"
    end

    private

    def check_at_least_one_day
        errors.add(:monday, "One day must be checked") if ([monday, tuesday, wednesday, thursday, friday].all? { |day| !day })
    end

    def check_only_one_day
        errors.add(:monday, "You must check only one day") if ([monday, tuesday, wednesday, thursday, friday].select { |day| day == true}).count > 1
    end

    def check_valid_hour
        errors.add(:hour, "must be between 8 and 14") if hour && (hour.hour < 8 || hour.hour > 14)
    end

    def check_teacher_day_overlap
        days = day_selected
        teacher && days.each do |day|
            unless teacher.lessons.find_by(hour: self.hour, "#{day}": true).blank?
                errors.add(:hour, "Overlaped with #{teacher.lessons.find_by(hour: self.hour, "#{day}": true)} on #{day.capitalize}")
            end
        end    
    end

    def check_group_day_overlap
        days = day_selected
        group && days.each do |day|
            unless group.lessons.find_by(hour: self.hour, "#{day}": true).blank?
                errors.add(:hour, "Overlaped with #{group.lessons.find_by(hour: self.hour, "#{day}": true)} on #{day.capitalize}")
            end
        end  
    end

    def day_selected
        days = %w[monday tuesday wednesday thursday friday]
        result = []
        days.each { |day| result.push(day) if send("#{day}") }
        result
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    load_and_authorize_resource

    before_action :set_lesson, only: [:show, :edit, :update]

    def index
        @lessons = Lesson.where(teacher: current_user).order(:group_id)
    end

    def new
        @lesson = Lesson.new
    end

    def show
    end

    def edit

    end

    def update
        if @lesson.update(lesson_params)
            teacher = Teacher.find(params[:lesson][:teacher_id])
            flash[:success] = "Lesson was successfully created"
            redirect_to teachers_path(teacher)
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def create
        @lesson = Lesson.new(lesson_params)
        if @lesson.save
            teacher = Teacher.find(params[:lesson][:teacher_id])
            flash[:success] = "Lesson was successfully created"
            redirect_to teacher_path(teacher)
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        @lesson.destroy
        flash[:danger] = "Lesson was successfully deleted"
        redirect_to lessons_path status: :unprocessable_entity
    end


    private

    def set_lesson
        @lesson = Lesson.find(params[:id])
    end

    def lesson_params
        params.require(:lesson).permit(:hour, :monday, :tuesday, :wednesday, :thursday, :friday, :group_id, :subject_id, :teacher_id)
    end
end

app/views/lessons/_form.html.erb
<%= render 'shared/errors_html', obj: @lesson %>

<div class="col-md-6 border rounded shadow-md p-3 mx-auto">
    <%= form_for(@lesson, :html => { role: "form" }) do |f| %>
        <div class="mb-3">
            <%= f.label :teacher, class:"form-label" %>
            <%= f.collection_select(:teacher_id, Teacher.where(id: current_user), :id, :full_name, {}, {:class => "form-select"}) %>
        </div>

        <div class="mb-3">
            <%= f.label :hour, class:"form-label" %>
            <%= f.time_field :hour, class:"form-control" %>
        </div>

        <div class="form-group">
            <p>Check only 1 day</p>
            <div class="mb-3 form-check">
                    <%= f.check_box :monday, class:"form-check-input" %>
                    <%= f.label :monday, class:"form-check-label" %>
            </div>
            <div class="mb-3 form-check">
                    <%= f.label :tuesday, class:"form-check-label" %>
                    <%= f.check_box :tuesday, class:"form-check-input" %>
            </div>
            <div class="mb-3 form-check">
                    <%= f.label :wednesday, class:"form-check-label" %>
                    <%= f.check_box :wednesday, class:"form-check-input" %>
            </div>
            <div class="mb-3 form-check">
                    <%= f.label :thursday, class:"form-check-label" %>
                    <%= f.check_box :thursday, class:"form-check-input" %>
            </div>
            <div class="mb-3 form-check">
                    <%= f.label :friday, class:"form-check-label" %>
                    <%= f.check_box :friday, class:"form-check-input" %>
            </div>
        </div>

        <div class="mb-3">
            <%= f.label :group, class:"form-label" %>
            <%= f.collection_select( :group_id, Group.order(:id), :id, :group_number, {:include_blank => 'Select the Group'}, {:class => "form-select"}) %>
        </div>

        <div class="mb-3">
            <%= f.label :subject, class:"form-label" %>
            <%= f.collection_select(:subject_id, Subject.order(:id), :id, :name, {:include_blank => 'Select the Subject'}, {:class => "form-select"}) %>
        </div>


        <%= f.submit(@lesson.new_record? ? "Create Lesson": "Update Lesson", class: "btn btn-primary btn-lg") %>
    <% end %>
</div>

app/views/lessons/edit.html.erb
<h1 class="text-center">Edit your Lesson</h1>

<%= render 'form' %>

app/views/lessons/index.html.erb
<% @lessons.each do |lesson| %>
    <div class="card w-50 mx-auto my-3 text-center">
        <div class="card-body">
            <h5 class="card-title"><%= lesson.subject.name %></h5>
            <p class="card-text"><%= lesson.check_lesson_days %></p>
            <%= link_to "Go to the lesson", lesson_path(lesson), class:"btn btn-primary" %>
        </div>
    </div>
<% end %>
<div class="w-50 my-3 mx-auto">
    <%= link_to "Back", teacher_path(@lessons[0].teacher), class: "btn btn-primary" %>
</div>

app/views/lessons/new.html.erb
<h1 class="text-center">Create a new Lesson</h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<div class="text-center w-50 my-3 mx-auto">
    <div class="card p-2">
    <div class="card-body">
        <h4 class="card-title text-decoration-underline text-primary"><%= @lesson.subject.name %></h4>
        <h5 class="card-title my-3"><%= @lesson.teacher.full_name %></h5>

        <h6 class="card-subtitle mb-2 text-muted my-2"><%= @lesson.hour.hour %>:00 - <%= @lesson.end_hour %>:00</h6>
        <h6 class="my-3"><%= @lesson.check_lesson_days %></h6>
        <% if @lesson&.group.students.blank? %>
            <h6 class="card-subtitle mb-2">No Students</h6>
        <% else %>
        <h6 class="card-subtitle mb-2">Students:</h6>
        <ul class="list-group list-group-flush my-2 w-50 mx-auto">
            <% @lesson.group.students.each do |student| %>
                <li class="list-group-item"><%= student.full_name %></li>
            <% end %>
        </ul>
        <% end %>
        <%= link_to "Edit", edit_lesson_path(@lesson), class:"card-link btn btn-warning" %>
        <%= link_to "Delete", lesson_path(@lesson), data: { "turbo-method" => :delete, "turbo-confirm" => "Are you sure you want to delete the Lesson?"}, class:"card-link btn btn-danger" %>
    </div>
    </div>
</div>
<div class="w-50 mx-auto">
    <%= link_to "Back", lessons_path, class: "btn btn-primary" %>
</div>