config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'
  devise_for :users

  resources :teachers, only: [:index, :show, :edit, :update]
  resources :students, only: [:index, :show]
  resources :lesson_plans, only: [:show]
  resources :lessons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/teacher.rb
class Teacher < User
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
    has_many :lessons
    after_create :send_welcome_email


    def week_schedule(day)
        lessons.where("#{day}": true).order(:hour)
    end

    def send_daily_schedule_email
        UserMailer.with(user: self).daily_schedule_email.deliver_now
    end

    def students
        students = []
        lessons.each do |lesson|
            students << lesson.students
        end
        students.flatten.uniq
    end

    def show_lessons
        result = lessons.map { |lesson| lesson.subject.name if lesson.subject }
        result.uniq
    end

    private
    def send_welcome_email
        UserMailer.with(user: self).welcome_email.deliver_now
    end
   
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    before_action :set_user, only: [:show, :edit]
    load_and_authorize_resource

    def index
        @teachers = Teacher.all
    end

    def show
    end

    def edit 
    end

    def update
        if @teacher.update(teacher_params)
            flash[:success] = "Your user was successfully updated"
            redirect_to teacher_path(@teacher)
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    private

    def set_user
        @teacher = Teacher.find(params[:id])
    end

    def teacher_params
        params.require(:teacher).permit(:first_name, :last_name, :email, :password, :password_confirmation).delete_if { |_k, v| v.blank? }
    end
end

app/views/teachers/edit.html.erb
<%= render 'shared/errors_html', obj: @teacher %>

<div class="col-md-6 border rounded shadow-md p-3 mx-auto">
    <h1>Edit your profile</h1>
    <%= form_for(@teacher, :html => { role: "form" }) do |f| %>
        <div class="mb-3">
            <%= f.label :first_name, class:"form-label" %>
            <%= f.text_field :first_name, class:"form-control" %>
        </div>

        <div class="mb-3">
            <%= f.label :last_name, class:"form-label" %>
            <%= f.text_field :last_name, class:"form-control" %>
        </div>

        <div class="mb-3">
            <%= f.label :email, class:"form-label" %>
            <%= f.email_field :email, class:"form-control" %>
        </div>
            

        <div class="mb-3">
            <%= f.label :password, class:"form-label" %>
            <%= f.password_field :password, class:"form-control" %>
        </div>

        <div class="mb-3">
            <%= f.label :password_confirmation, class:"form-label" %>
            <%= f.password_field :password_confirmation, class:"form-control" %>
        </div>

        <%= f.submit "Update Teacher", class: "btn btn-primary btn-lg" %>
    <% end %>
</div>

app/views/teachers/index.html.erb
<h3 class="text-center">Teachers</h3>

<% @teachers.each do |teacher| %>
    <div class="my-3 border rounded shadow-md w-50 p-3 text-center mx-auto">
        <%= gravatar_for teacher, size: 80 %>
        <h5 class="my-3"><%= teacher.full_name %></h5>
        <h6 class="text-muted"><%= teacher.email %></h6>
        <h6><%= teacher.show_lessons.to_sentence %></h6> 
               
    </div>
<% end %>

app/views/teachers/show.html.erb
<div class="w-100 d-flex flex-column align-items-center">
<h1>Teacher Profile</h1>
    <div class="my-3 border rounded shadow-md w-50 p-3 text-center">
        <%= gravatar_for @teacher, size: 80 %>
        <h5 class="my-3"><%= @teacher.full_name %></h5>
        <h6 class="text-muted"><%= @teacher.email %></h6>
    </div>

    <% if @teacher.lessons && @teacher == current_user %>
        <div class="w-50 text-center">   
            <%= link_to "Schedule", lesson_plan_path, class: "btn btn-primary me-2" %>
            <%= link_to "Lessons", lessons_path, class: "btn btn-success" %>
        </div>
    <% end %>
</div>












       

    