config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'
  devise_for :users

  resources :teachers, only: [:index, :show, :edit, :update]
  resources :students, only: [:index, :show]
  resources :lesson_plans, only: [:show]
  resources :lessons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/views/layouts/_messages.html.erb
<div class="row d-flex justify-content-center my-3">
    <div class="col-md-6">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= "#{name}"%> d-flex justify-content-between">
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
                <a href="#" class="btn-close" data-dismiss="alert"></a>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "SchoolApp", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user.is_a?(Teacher) %>
          <li class="nav-item">
            <%= link_to "Profile", teacher_path(current_user), class:"nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Lesson", new_lesson_path, class:"nav-link active" %>
          </li>
        <% end %>
        <% if current_user.is_a?(Student) %>
          <li class="nav-item">
            <%= link_to "Schedule", student_path(current_user), class:"nav-link active" %>
          </li>
        <% end %>
        <% if current_user.is_a?(Admin) %>
          <li class="nav-item">
            <%= link_to "Admin", rails_admin_path, class:"nav-link active" %>
          </li>
        <% end %>
        <li class="nav-item">
            <%= link_to "Teachers", teachers_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
            <%= link_to "Students", students_path, class:"nav-link active" %>
        </li>
      </ul>
      <div class="text-decoration-none d-flex">
        <% if user_signed_in? %>
          <% if current_user.is_a?(Teacher) %>
            <div class="dropdown me-3">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= gravatar_for current_user, size: 30 %>
                <%= current_user.email %>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Lessons", lessons_path, class:"dropdown-item"  %></li>
                <li><%= link_to "Edit your profil", edit_teacher_path(current_user), class:"dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Log out", destroy_user_session_path, data: {"turbo-method" => :delete }, class:"dropdown-item text-danger text-decoration-underline" %></li>
              </ul>
            </div>
          <% elsif current_user.is_a?(Student) %>
            <div class="btn btn-primary me-3">
              <%= gravatar_for current_user, size: 30 %>
              <%= link_to "#{current_user.email}", student_path(current_user), class:"text-white text-decoration-none" %>
            </div>
            <%= link_to "Log out", destroy_user_session_path, data: {"turbo-method" => :delete }, class:"btn btn-danger" %>
          <% else %>
             <%= link_to "Log out", destroy_user_session_path, data: {"turbo-method" => :delete }, class:"btn btn-danger" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolRubyApp</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>